server:
  port: 31001
  servlet:
    context-path: /cms/page
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://localhost:27017/xc_cms
      database: xc_cms